// layout.tsx
import type { Metadata } from 'next';
import { ClerkProvider } from '@clerk/nextjs';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import ClientUserInfo from './ClientUserInfo';


const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* Navbar */}
          <nav className="flex justify-between items-center p-4 bg-gray-100 shadow-md">
            {/* Left side: App name */}
            <div className="text-xl font-bold text-green-600">plant vs interview</div>

            {/* Client-side user info */}
            <ClientUserInfo /> {/* Insert the client component here */}
          </nav>

          {/* Main content */}
          {children}

          {/* Footer */}
          <footer className="p-4 bg-gray-100 text-center text-sm text-gray-500">
            © {new Date().getFullYear()} Plant vs Interview. All rights reserved.
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}




